version: "3"
services:
  handson-ml3:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.gpu
      args:
        - username=devel
        - userid=1001
    container_name: handson-ml3
    image: ageron/handson-ml3:latest-gpu
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8888:8888"
      - "6006:6006"
      - "3000:3000"
    volumes:
      - ../:/home/devel/handson-ml3
    #command: /opt/conda/envs/homl3/bin/jupyter lab --ip='0.0.0.0' --port=8888 --no-browser
    #command: /opt/conda/bin/conda activate homl3 && /opt/conda/envs/homl3/bin/jupyter lab --ip='0.0.0.0' --port=8888 --no-browser
    command: bash -c "./docker/start.sh"
    deploy:
     resources:
       reservations:
         devices:
         - capabilities: [gpu]
